services:
  postgres:
    image: postgres:17.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres # test credentials (see README)
      POSTGRES_PASSWORD: postgres # test credentials (see README)
      POSTGRES_DB: portfolio
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/portfolio
      SPRING_DATASOURCE_USERNAME: postgres # test credentials (see README)
      SPRING_DATASOURCE_PASSWORD: postgres # test credentials (see README)
    ports:
      - '8080:8080'
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - '4200:80'
    depends_on:
      - backend
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  postgres_data: