services:
  postgres:
    image: postgres:15.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres # test credentials (see README)
      POSTGRES_PASSWORD: postgres # test credentials (see README)
      POSTGRES_DB: portfolio
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

#volumes:
#  postgres_data:

networks:
  backend: